/**
 * @fileoverview gRPC-Web generated client stub for game
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: game.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.game = require('./game_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.game.GameServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.game.GameServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.game.JoinRequest,
 *   !proto.game.JoinResponse>}
 */
const methodDescriptor_GameService_JoinGame = new grpc.web.MethodDescriptor(
  '/game.GameService/JoinGame',
  grpc.web.MethodType.UNARY,
  proto.game.JoinRequest,
  proto.game.JoinResponse,
  /**
   * @param {!proto.game.JoinRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.game.JoinResponse.deserializeBinary
);


/**
 * @param {!proto.game.JoinRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.game.JoinResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.game.JoinResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.game.GameServiceClient.prototype.joinGame =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/game.GameService/JoinGame',
      request,
      metadata || {},
      methodDescriptor_GameService_JoinGame,
      callback);
};


/**
 * @param {!proto.game.JoinRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.game.JoinResponse>}
 *     Promise that resolves to the response
 */
proto.game.GameServicePromiseClient.prototype.joinGame =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/game.GameService/JoinGame',
      request,
      metadata || {},
      methodDescriptor_GameService_JoinGame);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.game.MoveRequest,
 *   !proto.game.MoveResponse>}
 */
const methodDescriptor_GameService_MakeMove = new grpc.web.MethodDescriptor(
  '/game.GameService/MakeMove',
  grpc.web.MethodType.UNARY,
  proto.game.MoveRequest,
  proto.game.MoveResponse,
  /**
   * @param {!proto.game.MoveRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.game.MoveResponse.deserializeBinary
);


/**
 * @param {!proto.game.MoveRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.game.MoveResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.game.MoveResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.game.GameServiceClient.prototype.makeMove =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/game.GameService/MakeMove',
      request,
      metadata || {},
      methodDescriptor_GameService_MakeMove,
      callback);
};


/**
 * @param {!proto.game.MoveRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.game.MoveResponse>}
 *     Promise that resolves to the response
 */
proto.game.GameServicePromiseClient.prototype.makeMove =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/game.GameService/MakeMove',
      request,
      metadata || {},
      methodDescriptor_GameService_MakeMove);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.game.StreamRequest,
 *   !proto.game.GameState>}
 */
const methodDescriptor_GameService_StreamGameState = new grpc.web.MethodDescriptor(
  '/game.GameService/StreamGameState',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.game.StreamRequest,
  proto.game.GameState,
  /**
   * @param {!proto.game.StreamRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.game.GameState.deserializeBinary
);


/**
 * @param {!proto.game.StreamRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.game.GameState>}
 *     The XHR Node Readable Stream
 */
proto.game.GameServiceClient.prototype.streamGameState =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/game.GameService/StreamGameState',
      request,
      metadata || {},
      methodDescriptor_GameService_StreamGameState);
};


/**
 * @param {!proto.game.StreamRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.game.GameState>}
 *     The XHR Node Readable Stream
 */
proto.game.GameServicePromiseClient.prototype.streamGameState =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/game.GameService/StreamGameState',
      request,
      metadata || {},
      methodDescriptor_GameService_StreamGameState);
};


module.exports = proto.game;

